version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Optional: set shared memory limit
    shm_size: 128mb
    networks:
      - food_network
  
  nats:
    image: nats:latest
    command: -js -sd /data
    ports:
      - "4222:4222" # Client port
      - "8222:8222" # HTTP management port
    volumes:
      - nats_data:/data
    networks:
      - food_network

volumes:
  postgres_data:
  nats_data:
      
networks:
  food_network:
    driver: bridge